### ISSUE TITLE
devDependencies inside prod environment

### ISSUE THREAD

**Issue by lkleuver** [osenvosem/react-mobx-boilerplate#2]
When deploying (my extended version of) the boilerplate to Heroku I noticed it was failing because it was depending on devDependencies while start:prod. I fixed it with the following code:

in server.js
`if (process.env.NODE_ENV === 'development') {
  // Development
  const webpack = require('webpack');
  const webpackDevServer = require('webpack-dev-server');
  const webpackDevConfig = require('../webpack.dev.js');`

Not sure if this is the correct approach, but it works :)

(the one other thing I needed was a json loader test inside webpack config for some modules)

Great boilerplate!

**Comment by osenvosem** [comment]
Thank you. I moved those imports in the "development" `if` block.
