### ISSUE TITLE
Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

### ISSUE THREAD

**Issue by crapthings** [osenvosem/react-mobx-boilerplate#3]
node -v

```
v4.4.7
```

should i use node v6 ?

let babelConfig = require('../package').babelConfig.server;
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
[nodemon] app crashed - waiting for file changes before starting...

**Comment by osenvosem** [comment]
Just update node to the latest version (v6.3.1 is the current one), or maybe use "strict mode".

**Comment by crapthings** [comment]
yes strict mode is better

most people are stay with 4

**Comment by osenvosem** [comment]
@crapthings why?

**Comment by crapthings** [comment]
at lease work with 4

just clone and npm install

**Comment by osenvosem** [comment]
@crapthings I meant why "most people are stay with 4"?

**Comment by crapthings** [comment]
maybe because it's LTS right now?

**Comment by crapthings** [comment]
why not just use let or var ???

```
var path = require('path');

// To resolve shared folder during server development transpling
var sharedFolder = require('babel-resolver')(
  path.resolve(process.cwd(), 'app/shared')
);

let babelConfig = require('../package').babelConfig.server;
babelConfig = Object.assign(babelConfig, { resolveModuleSource: sharedFolder });
```

**Comment by osenvosem** [comment]
@crapthings ok, I will fix that.

**Comment by osenvosem** [comment]
@crapthings ok, you may try it.

**Comment by crapthings** [comment]
great job

this boilerplate help me learn mobx better

+100

**Comment by osenvosem** [comment]
@crapthings thank you.
